"""Add encryption_key to User model

Revision ID: fd1c21a8e907
Revises: e19dd3afce96
Create Date: 2024-08-20 21:57:30.433453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd1c21a8e907'
down_revision = 'e19dd3afce96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryption_key', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('encryption_key')

    # ### end Alembic commands ###
